# Site settings
title: Rohan Sogani Homepage
motto: Life is a series of lessons, learn from it and enjoy!!
email: soganirohan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  May the source be with you!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rohansogani.github.io" # the base hostname & protocol for your site
github_username:  RohanSogani
twitter_username: RMS_18
facebook_username: RohanSogani

# Build settings
markdown: kramdown
